// Color scheme definitions
// Each theme has complementary status colors that work with the overall vibe

export const themes = {
  sage: {
    id: 'sage',
    name: 'Sage',
    background: '#FAF9F6',
    backgroundRgb: '250, 249, 246',
    cta: '#6366F1',
    ctaHover: '#4F46E5',
    ctaText: '#FFFFFF',
    headerAvailable: '#22C55E',
    headerOpen: '#F59E0B',
    headerBusy: '#F4A69A',
    statusAvailable: '#9CAF88',
    statusOpen: '#F4D03F',
    statusBusy: '#F4A69A',
    circleRock: '#9CAF88',
    circleWoodstock: '#94A3B8',
    circleNyc: '#F4A69A',
    textPrimary: '#1F2937',
    textSecondary: '#6B7280',
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    background: '#F0F9FF',
    backgroundRgb: '240, 249, 255',
    cta: '#0EA5E9',
    ctaHover: '#0284C7',
    ctaText: '#FFFFFF',
    headerAvailable: '#14B8A6',
    headerOpen: '#FBBF24',
    headerBusy: '#FB7185',
    statusAvailable: '#5EEAD4',
    statusOpen: '#FCD34D',
    statusBusy: '#FDA4AF',
    circleRock: '#5EEAD4',
    circleWoodstock: '#7DD3FC',
    circleNyc: '#FDA4AF',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    background: '#FFFBEB',
    backgroundRgb: '255, 251, 235',
    cta: '#F97316',
    ctaHover: '#EA580C',
    ctaText: '#FFFFFF',
    headerAvailable: '#84CC16',
    headerOpen: '#EAB308',
    headerBusy: '#F87171',
    statusAvailable: '#BEF264',
    statusOpen: '#FDE047',
    statusBusy: '#FCA5A5',
    circleRock: '#BEF264',
    circleWoodstock: '#FDBA74',
    circleNyc: '#FCA5A5',
    textPrimary: '#1C1917',
    textSecondary: '#78716C',
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender',
    background: '#FAF5FF',
    backgroundRgb: '250, 245, 255',
    cta: '#A855F7',
    ctaHover: '#9333EA',
    ctaText: '#FFFFFF',
    headerAvailable: '#34D399',
    headerOpen: '#FBBF24',
    headerBusy: '#F472B6',
    statusAvailable: '#6EE7B7',
    statusOpen: '#FCD34D',
    statusBusy: '#F9A8D4',
    circleRock: '#6EE7B7',
    circleWoodstock: '#C4B5FD',
    circleNyc: '#F9A8D4',
    textPrimary: '#1E1B4B',
    textSecondary: '#6B7280',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    background: '#0F172A',
    backgroundRgb: '15, 23, 42',
    cta: '#8B5CF6',
    ctaHover: '#7C3AED',
    ctaText: '#FFFFFF',
    headerAvailable: '#10B981',
    headerOpen: '#F59E0B',
    headerBusy: '#F43F5E',
    statusAvailable: '#34D399',
    statusOpen: '#FBBF24',
    statusBusy: '#FB7185',
    circleRock: '#34D399',
    circleWoodstock: '#A78BFA',
    circleNyc: '#FB7185',
    textPrimary: '#F8FAFC',
    textSecondary: '#94A3B8',
  },
};

export const themeOrder = ['midnight', 'sage', 'ocean', 'sunset', 'lavender'];

export const getNextTheme = (currentThemeId) => {
  const currentIndex = themeOrder.indexOf(currentThemeId);
  const nextIndex = (currentIndex + 1) % themeOrder.length;
  return themeOrder[nextIndex];
};
